#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

a = ARGV[0]

system "java -cp bin/:lib/antlr-4.4-complete.jar WACCMain #{a}"

exit $?.exitstatus
