package Intsr;

public enum Instruc {
	
	PUSH, POP, MOV, LDR, BL, B, SUB, SUBS, ADD, SMULL, BLNE, ADDS, AND, OR, EOR, STR, STRB, RSBS, CMP, MOVLT, MOVGE, MOVLE, MOVGT, LDRSB, MOVNE, MOVEQ, BEQ, BLVS, BLEQ, LDRNE, LDREQ;
	
}
