package Intsr;

public enum Instruc {
	
	PUSH, POP, MOV, LDR, LDRLT, LDRCS, BL, BLLT, BLCS, B, SUB, 
	SUBS, ADD, SMULL, BLNE, ADDS, AND, OR, ORR, EOR, STR, STRB, 
	RSBS, CMP, MOVLT, MOVGE, MOVLE, MOVGT, LDRSB, MOVNE, MOVEQ, 
	BEQ, BLVS, BLEQ, LDRNE, LDREQ;
	
}
